/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#426258',
        'on-secondary-fixed': '#3e403f',
        'surface-container-high': '#e2e9ec',
        'surface-variant': '#dbe4e7',
        'error-container': '#fe8983',
        'primary-fixed-dim': '#b9dcd0',
        'on-primary': '#defff3',
        'on-tertiary': '#ecffdb',
        'secondary-container': '#e2e3e1',
        'tertiary-fixed': '#e6fad5',
        'surface-container-highest': '#dbe4e7',
        secondary: '#5e5f5e',
        'on-tertiary-container': '#506144',
        'primary-fixed': '#c7eade',
        'on-error': '#fff7f6',
        'surface-container': '#eaeff1',
        background: '#f8f9fa',
        'primary-container': '#c7eade',
        'on-secondary-fixed-variant': '#5a5c5b',
        'secondary-dim': '#525352',
        'on-surface-variant': '#586064',
        'surface-container-low': '#f1f4f6',
        'surface-container-lowest': '#ffffff',
        primary: '#45655b',
        'on-secondary': '#f9f9f7',
        'secondary-fixed-dim': '#d4d5d3',
        'inverse-on-surface': '#9b9d9e',
        'inverse-surface': '#0c0f10',
        outline: '#737c7f',
        'on-primary-container': '#39584e',
        'on-background': '#2b3437',
        'inverse-primary': '#d3f6e9',
        tertiary: '#536447',
        'on-surface': '#2b3437',
        'outline-variant': '#abb3b7',
        'surface-dim': '#d1dce0',
        'tertiary-dim': '#47583c',
        'on-error-container': '#752121',
        surface: '#f8f9fa',
        error: '#9f403d',
        'on-tertiary-fixed-variant': '#5a6b4e',
        'tertiary-container': '#e6fad5',
        'secondary-fixed': '#e2e3e1',
        'primary-dim': '#39584f',
        'on-tertiary-fixed': '#3e4e33',
        'on-primary-fixed': '#26453c',
        'on-secondary-container': '#505251',
        'error-dim': '#4e0309',
        'surface-bright': '#f8f9fa',
        'surface-tint': '#45655b',
        'tertiary-fixed-dim': '#d8ecc7',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
